id: I9244B93E
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:39:46.212753
last_modified: 2023-02-10 00:39:46.212909
source_metadata:
  title: Udānavarga
  language: sa
bases:
  C9C5:
    base_file: C9C5.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
